## UCI Adult Income Dataset—Data Cleaning and Preprocessing
This notebook is focused on the data preparation, cleaning and preprocessing for the UCI Adult Income Dataset.

In [313]:
#import libraries
import pandas as pd
import numpy as np
import os

In [314]:
#get working directory
current_dir = os.getcwd()
#go one directoory up to the root directory
project_root_dir = os.path.dirname(current_dir)
#define paths to the data folders
data_dir = os.path.join(project_root_dir, "data")
raw_dir = os.path.join(data_dir, "raw")
processed_dir =  os.path.join(data_dir, "processed")
#define paths to the results folders
result_dir =  os.path.join(project_root_dir, "result")
#define paths to the docs folders
docs_dir =  os.path.join(project_root_dir, "docs")

#creaye directories if they don't exist
os.makedirs(raw_dir,exist_ok = True)
os.makedirs(processed_dir,exist_ok = True)
os.makedirs(result_dir,exist_ok = True )      
os.makedirs(docs_dir,exist_ok = True)                        

## Read in the data

In [315]:
adult_data_finename = os.path.join(raw_dir, "adult.csv")
adult_df = pd.read_csv(adult_data_finename, header = None, na_values = "?", skipinitialspace = True)
adult_df.head(10)

0                 1       2          3   4                      5   \
0  39         State-gov   77516  Bachelors  13          Never-married   
1  50  Self-emp-not-inc   83311  Bachelors  13     Married-civ-spouse   
2  38           Private  215646    HS-grad   9               Divorced   
3  53           Private  234721       11th   7     Married-civ-spouse   
4  28           Private  338409  Bachelors  13     Married-civ-spouse   
5  37           Private  284582    Masters  14     Married-civ-spouse   
6  49           Private  160187        9th   5  Married-spouse-absent   
7  52  Self-emp-not-inc  209642    HS-grad   9     Married-civ-spouse   
8  31           Private   45781    Masters  14          Never-married   
9  42           Private  159449  Bachelors  13     Married-civ-spouse   

                  6              7      8       9      10  11  12  \
0       Adm-clerical  Not-in-family  White    Male   2174   0  40   
1    Exec-managerial        Husband  White    Male      0   0  13   
2  Handlers-cleaners  Not-in-family  White    Male      0   0  40   
3  Handlers-cleaners        Husband  Black    Male      0   0  40   
4     Prof-specialty           Wife  Black  Female      0   0  40   
5    Exec-managerial           Wife  White  Female      0   0  40   
6      Other-service  Not-in-family  Black  Female      0   0  16   
7    Exec-managerial        Husband  White    Male      0   0  45   
8     Prof-specialty  Not-in-family  White  Female  14084   0  50   
9    Exec-managerial        Husband  White    Male   5178   0  40   

              13     14  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4           Cuba  <=50K  
5  United-States  <=50K  
6        Jamaica  <=50K  
7  United-States   >50K  
8  United-States   >50K  
9  United-States   >50K

In [316]:
adult_df.shape 

(32561, 15)

In [317]:
adult_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       32561 non-null  int64 
 1   1       30725 non-null  object
 2   2       32561 non-null  int64 
 3   3       32561 non-null  object
 4   4       32561 non-null  int64 
 5   5       32561 non-null  object
 6   6       30718 non-null  object
 7   7       32561 non-null  object
 8   8       32561 non-null  object
 9   9       32561 non-null  object
 10  10      32561 non-null  int64 
 11  11      32561 non-null  int64 
 12  12      32561 non-null  int64 
 13  13      31978 non-null  object
 14  14      32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


## data cleaning 
## Assign proper column names to the columns

In [318]:
adult_df.columns =["age","workclass","fnlwht","education","education_num","martual_status","occupation","relationship","race","sex","capital_num","capital_loss","hours_per_week","native_country","income"]

In [319]:
adult_df.head(10)

age         workclass  fnlwht  education  education_num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   
5   37           Private  284582    Masters             14   
6   49           Private  160187        9th              5   
7   52  Self-emp-not-inc  209642    HS-grad              9   
8   31           Private   45781    Masters             14   
9   42           Private  159449  Bachelors             13   

          martual_status         occupation   relationship   race     sex  \
0          Never-married       Adm-clerical  Not-in-family  White    Male   
1     Married-civ-spouse    Exec-managerial        Husband  White    Male   
2               Divorced  Handlers-cleaners  Not-in-family  White    Male   
3     Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4     Married-civ-spouse     Prof-specialty           Wife  Black  Female   
5     Married-civ-spouse    Exec-managerial           Wife  White  Female   
6  Married-spouse-absent      Other-service  Not-in-family  Black  Female   
7     Married-civ-spouse    Exec-managerial        Husband  White    Male   
8          Never-married     Prof-specialty  Not-in-family  White  Female   
9     Married-civ-spouse    Exec-managerial        Husband  White    Male   

   capital_num  capital_loss  hours_per_week native_country income  
0         2174             0              40  United-States  <=50K  
1            0             0              13  United-States  <=50K  
2            0             0              40  United-States  <=50K  
3            0             0              40  United-States  <=50K  
4            0             0              40           Cuba  <=50K  
5            0             0              40  United-States  <=50K  
6            0             0              16        Jamaica  <=50K  
7            0             0              45  United-States   >50K  
8        14084             0              50  United-States   >50K  
9         5178             0              40  United-States   >50K

## Understanding the dataset
- age: represents the age of the person, ranging from 17 to 90
- workclass: represents the employment status of the person.
- fnlwht: the weight the individual represents in the population
- 

In [320]:
np.unique(adult_df.age.to_list())

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 90])

In [321]:
np.unique(adult_df.workclass.to_list())

array(['Federal-gov', 'Local-gov', 'Never-worked', 'Private',
       'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay',
       'nan'], dtype='<U32')

In [322]:
np.unique(adult_df.fnlwht.to_list())

array([  12285,   13769,   14878, ..., 1366120, 1455435, 1484705])

In [323]:
np.unique(adult_df.education.to_list())

array(['10th', '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th',
       'Assoc-acdm', 'Assoc-voc', 'Bachelors', 'Doctorate', 'HS-grad',
       'Masters', 'Preschool', 'Prof-school', 'Some-college'],
      dtype='<U12')

In [324]:
np.unique(adult_df.education_num.to_list())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [325]:
np.unique(adult_df.martual_status.to_list())

array(['Divorced', 'Married-AF-spouse', 'Married-civ-spouse',
       'Married-spouse-absent', 'Never-married', 'Separated', 'Widowed'],
      dtype='<U21')

In [326]:
np.unique(adult_df.occupation.to_list())

array(['Adm-clerical', 'Armed-Forces', 'Craft-repair', 'Exec-managerial',
       'Farming-fishing', 'Handlers-cleaners', 'Machine-op-inspct',
       'Other-service', 'Priv-house-serv', 'Prof-specialty',
       'Protective-serv', 'Sales', 'Tech-support', 'Transport-moving',
       'nan'], dtype='<U32')

In [327]:
np.unique(adult_df.relationship.to_list())

array(['Husband', 'Not-in-family', 'Other-relative', 'Own-child',
       'Unmarried', 'Wife'], dtype='<U14')

In [328]:
np.unique(adult_df.race.to_list())

array(['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other',
       'White'], dtype='<U18')

In [329]:
np.unique(adult_df.sex.to_list())

array(['Female', 'Male'], dtype='<U6')

In [330]:
np.unique(adult_df.capital_num.to_list())

array([    0,   114,   401,   594,   914,   991,  1055,  1086,  1111,
        1151,  1173,  1409,  1424,  1455,  1471,  1506,  1639,  1797,
        1831,  1848,  2009,  2036,  2050,  2062,  2105,  2174,  2176,
        2202,  2228,  2290,  2329,  2346,  2354,  2387,  2407,  2414,
        2463,  2538,  2580,  2597,  2635,  2653,  2829,  2885,  2907,
        2936,  2961,  2964,  2977,  2993,  3103,  3137,  3273,  3325,
        3411,  3418,  3432,  3456,  3464,  3471,  3674,  3781,  3818,
        3887,  3908,  3942,  4064,  4101,  4386,  4416,  4508,  4650,
        4687,  4787,  4865,  4931,  4934,  5013,  5060,  5178,  5455,
        5556,  5721,  6097,  6360,  6418,  6497,  6514,  6723,  6767,
        6849,  7298,  7430,  7443,  7688,  7896,  7978,  8614,  9386,
        9562, 10520, 10566, 10605, 11678, 13550, 14084, 14344, 15020,
       15024, 15831, 18481, 20051, 22040, 25124, 25236, 27828, 34095,
       41310, 99999])

In [331]:
np.unique(adult_df.capital_loss.to_list())

array([   0,  155,  213,  323,  419,  625,  653,  810,  880,  974, 1092,
       1138, 1258, 1340, 1380, 1408, 1411, 1485, 1504, 1539, 1564, 1573,
       1579, 1590, 1594, 1602, 1617, 1628, 1648, 1651, 1668, 1669, 1672,
       1719, 1721, 1726, 1735, 1740, 1741, 1755, 1762, 1816, 1825, 1844,
       1848, 1876, 1887, 1902, 1944, 1974, 1977, 1980, 2001, 2002, 2042,
       2051, 2057, 2080, 2129, 2149, 2163, 2174, 2179, 2201, 2205, 2206,
       2231, 2238, 2246, 2258, 2267, 2282, 2339, 2352, 2377, 2392, 2415,
       2444, 2457, 2467, 2472, 2489, 2547, 2559, 2603, 2754, 2824, 3004,
       3683, 3770, 3900, 4356])

In [332]:

np.unique(adult_df.hours_per_week.to_list())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       70, 72, 73, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 94, 95, 96, 97, 98, 99])

In [333]:
np.unique(adult_df.hours_per_week.to_list())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       70, 72, 73, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 94, 95, 96, 97, 98, 99])

In [334]:
np.unique(adult_df.income.to_list())

array(['<=50K', '>50K'], dtype='<U5')

In [335]:
adult_df.isnull().sum()


age                  0
workclass         1836
fnlwht               0
education            0
education_num        0
martual_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_num          0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [336]:
adult_df['workclass'] = adult_df['workclass'].fillna('unknown')
adult_df['native_country'] = adult_df['native_country'].fillna('other')
adult_df['occupation'] = adult_df['occupation'].fillna('unknown')

In [337]:
adult_df.isnull().sum()

age               0
workclass         0
fnlwht            0
education         0
education_num     0
martual_status    0
occupation        0
relationship      0
race              0
sex               0
capital_num       0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

## Deal with duplicates


In [338]:
adult_df.duplicated().sum()

24

In [339]:
adult_df[adult_df.duplicated(keep=False)]

age         workclass  fnlwht     education  education_num  \
2303    90           Private   52386  Some-college             10   
3917    19           Private  251579  Some-college             10   
4325    25           Private  308144     Bachelors             13   
4767    21           Private  250051  Some-college             10   
4881    25           Private  308144     Bachelors             13   
4940    38           Private  207202       HS-grad              9   
5104    90           Private   52386  Some-college             10   
5579    27           Private  255582       HS-grad              9   
5805    20           Private  107658  Some-college             10   
5842    25           Private  195994       1st-4th              2   
6990    19           Private  138153  Some-college             10   
7053    49  Self-emp-not-inc   43479  Some-college             10   
7920    49           Private   31267       7th-8th              4   
8080    21           Private  243368     Preschool              1   
8679    28           Private  274679       Masters             14   
9171    21           Private  250051  Some-college             10   
10367   42           Private  204235  Some-college             10   
11631   20           Private  107658  Some-college             10   
11965   46           Private  133616  Some-college             10   
13084   25           Private  195994       1st-4th              2   
15059   21           Private  243368     Preschool              1   
15189   19           Private  146679  Some-college             10   
16297   46           Private  173243       HS-grad              9   
16846   35           Private  379959       HS-grad              9   
16975   30           Private  144593       HS-grad              9   
17040   46           Private  173243       HS-grad              9   
17673   19           Private   97261       HS-grad              9   
17916   44           Private  367749     Bachelors             13   
18555   30           Private  144593       HS-grad              9   
18698   19           Private   97261       HS-grad              9   
21103   23           Private  240137       5th-6th              3   
21318   19           Private  138153  Some-college             10   
21490   19           Private  146679  Some-college             10   
21875   49           Private   31267       7th-8th              4   
22300   25           Private  195994       1st-4th              2   
22367   44           Private  367749     Bachelors             13   
22494   49  Self-emp-not-inc   43479  Some-college             10   
25624   39           Private   30916       HS-grad              9   
25872   23           Private  240137       5th-6th              3   
26313   28           Private  274679       Masters             14   
28230   27           Private  255582       HS-grad              9   
28522   42           Private  204235  Some-college             10   
28846   39           Private   30916       HS-grad              9   
29157   38           Private  207202       HS-grad              9   
30845   46           Private  133616  Some-college             10   
31993   19           Private  251579  Some-college             10   
32404   35           Private  379959       HS-grad              9   

           martual_status         occupation   relationship  \
2303        Never-married      Other-service  Not-in-family   
3917        Never-married      Other-service      Own-child   
4325        Never-married       Craft-repair  Not-in-family   
4767        Never-married     Prof-specialty      Own-child   
4881        Never-married       Craft-repair  Not-in-family   
4940   Married-civ-spouse  Machine-op-inspct        Husband   
5104        Never-married      Other-service  Not-in-family   
5579        Never-married  Machine-op-inspct  Not-in-family   
5805        Never-married       Tech-support  Not-in-family   
5842        Never-married    Priv-house-serv  Not-in-family   
6

In [340]:
adult_df = adult_df.drop_duplicates()

In [341]:
adult_df.duplicated().sum()

0

In [342]:
adult_df.shape

(32537, 15)

## Standardize Categorical Variables 

In [343]:
categorical_cols = adult_df.columns[adult_df.dtypes == object]
for col in categorical_cols:
    adult_df[col] = adult_df[col].str.strip().str.lower()


In [344]:
adult_df

age         workclass  fnlwht   education  education_num  \
0       39         state-gov   77516   bachelors             13   
1       50  self-emp-not-inc   83311   bachelors             13   
2       38           private  215646     hs-grad              9   
3       53           private  234721        11th              7   
4       28           private  338409   bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           private  257302  assoc-acdm             12   
32557   40           private  154374     hs-grad              9   
32558   58           private  151910     hs-grad              9   
32559   22           private  201490     hs-grad              9   
32560   52      self-emp-inc  287927     hs-grad              9   

           martual_status         occupation   relationship   race     sex  \
0           never-married       adm-clerical  not-in-family  white    male   
1      married-civ-spouse    exec-managerial        husband  white    male   
2                divorced  handlers-cleaners  not-in-family  white    male   
3      married-civ-spouse  handlers-cleaners        husband  black    male   
4      married-civ-spouse     prof-specialty           wife  black  female   
...                   ...                ...            ...    ...     ...   
32556  married-civ-spouse       tech-support           wife  white  female   
32557  married-civ-spouse  machine-op-inspct        husband  white    male   
32558             widowed       adm-clerical      unmarried  white  female   
32559       never-married       adm-clerical      own-child  white    male   
32560  married-civ-spouse    exec-managerial           wife  white  female   

       capital_num  capital_loss  hours_per_week native_country income  
0             2174             0              40  united-states  <=50k  
1                0             0              13  united-states  <=50k  
2                0             0              40  united-states  <=50k  
3                0             0              40  united-states  <=50k  
4                0             0              40           cuba  <=50k  
...            ...           ...             ...            ...    ...  
32556            0             0              38  united-states  <=50k  
32557            0             0              40  united-states   >50k  
32558            0             0              40  united-states  <=50k  
32559            0             0              20  united-states  <=50k  
32560        15024             0              40  united-states   >50k  

[32537 rows x 15 columns]

In [345]:
categorical_cols

Index(['workclass', 'education', 'martual_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

## Re-code the workclass columnn

In [346]:
adult_df['workclass'].unique()

array(['state-gov', 'self-emp-not-inc', 'private', 'federal-gov',
       'local-gov', 'unknown', 'self-emp-inc', 'without-pay',
       'never-worked'], dtype=object)

In [347]:
adult_df['workclass']=adult_df['workclass'].replace({
    'state-gov':'government',
    'loc-gov':'government',
    'federal-gov':'government',
    'self-emp-not-inc':'self-employment',
    'self-emp-inc':'self-employment',
    'never-worked':'unemployed',
    'without-pay':'voluntary',})

## Re-code the education columnn

In [348]:
adult_df['education'].unique()

array(['bachelors', 'hs-grad', '11th', 'masters', '9th', 'some-college',
       'assoc-acdm', 'assoc-voc', '7th-8th', 'doctorate', 'prof-school',
       '5th-6th', '10th', '1st-4th', 'preschool', '12th'], dtype=object)

In [349]:
adult_df['education_level']=adult_df['education'].map({
    'bachelors':'tertiary',
    'masters':'tertiary',
    'doctorate':'tertiary',
    'prof-school':'tertiary',
    'some-college':'some college',
    'assoc-acdm':'associate',
    'assoc-voc':'associate',
    'hs-grad':'high school graduate',
    '11th':'secondary',
    '12th':'secondary',
    '10th':'secondary',
    '9th':'secondary',
    '7th-8th':'primary',
    '5th-6th':'primary',
    '1st-4th':'primary',
    'preschool': 'preschool'})

In [350]:
adult_df.columns

Index(['age', 'workclass', 'fnlwht', 'education', 'education_num',
       'martual_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_num', 'capital_loss', 'hours_per_week', 'native_country',
       'income', 'education_level'],
      dtype='object')

In [351]:
adult_df['education_level'].unique()

array(['tertiary', 'high school graduate', 'secondary', 'some college',
       'associate', 'primary', 'preschool'], dtype=object)

## Re-code the marital_status columnn

In [352]:
adult_df['martual_status'].unique()

array(['never-married', 'married-civ-spouse', 'divorced',
       'married-spouse-absent', 'separated', 'married-af-spouse',
       'widowed'], dtype=object)

In [353]:
adult_df['martual_status']= adult_df['martual_status'].replace({
    'never-married':'single',
    'married-civ-spouse':'married',
    'married-spouse-absent':'divorced or separated',
    'divorced':'divorced or separated',
    'separated':'divorced or separated',
    'married-af-spouse':'married',
})

In [354]:
adult_df.columns

Index(['age', 'workclass', 'fnlwht', 'education', 'education_num',
       'martual_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_num', 'capital_loss', 'hours_per_week', 'native_country',
       'income', 'education_level'],
      dtype='object')

In [355]:
adult_df['martual_status'].unique()

array(['single', 'married', 'divorced or separated', 'widowed'],
      dtype=object)

## Re-code the occupation columnn

In [356]:
adult_df['occupation'].unique()

array(['adm-clerical', 'exec-managerial', 'handlers-cleaners',
       'prof-specialty', 'other-service', 'sales', 'craft-repair',
       'transport-moving', 'farming-fishing', 'machine-op-inspct',
       'tech-support', 'unknown', 'protective-serv', 'armed-forces',
       'priv-house-serv'], dtype=object)

In [357]:
adult_df['occupation_grouped']=adult_df['occupation'].map({
    'adm-clerical':'white collar',
    'exec-managerial':'white collar',
    'handlers-cleaners':'blue collar',
    'prof-specialty':'white collar',
    'other-service':'service',
    'sales':'white collar',
    'craft-repair':'blue collar',
    'transport-moving':'blue collar',
    'farming-fishing':'blue collar',
    'machine-op-inspct':'blue collar',
    'tech-support':'white collar',
    'unknown':'unknown',
    'protective-serv':'service',
    'armed-forces':'military',
    'priv-house-serv':'service',
    
})

In [358]:
adult_df['occupation_grouped'].unique()

array(['white collar', 'blue collar', 'service', 'unknown', 'military'],
      dtype=object)

## Re-code the Relationship columnn

In [361]:
adult_df['relationship_group'] = adult_df['relationship'].replace({
    'not-in-family': 'single',
    'husband': 'male spouse',
    'wife': 'female spouse',
    'own-child': 'child',
    'unmarried': 'single',
    'other-relative' : 'extended relative',
})

In [362]:
adult_df['relationship_group'].unique()

array(['single', 'male spouse', 'female spouse', 'child',
       'extended relative'], dtype=object)

## Re-code the race columnn

In [363]:
adult_df['race'] = adult_df['race'].replace({
    'White': 'white',
    'Asian-Pac-Islander': 'asian or pacific islander',
    'Amer-Indian-Eskimo': 'american indian or eskimo',
    'Black': 'black',
    'Other': 'other'
})

In [364]:
adult_df['race'].unique()

array(['white', 'black', 'asian-pac-islander', 'amer-indian-eskimo',
       'other'], dtype=object)

## Re-code the native_country column

In [365]:
adult_df.loc[:,'native_region'] = adult_df['native_country'].map({
    'united-states': 'north america',
    'cambodia': 'asia',
    'england': 'europe',
    'puerto-rico': 'north america',
    'canada': 'north america',
    'germany': 'europe',
    'outlying-us(guam-usvi-etc)': 'north america',
    'india': 'asia',
    'japan': 'asia',
    'greece': 'europe',
    'south': 'south america',
    'china': 'asia',
    'cuba': 'central america',
    'iran': 'asia',
    'honduras': 'central america',
    'philippines': 'asia',
    'italy': 'europe',
    'poland': 'europe',
    'jamaica': 'central america',
    'vietnam': 'asia',
    'mexico': 'north america',
    'portugal': 'europe',
    'ireland': 'europe',
    'france': 'europe',
    'dominican-republic': 'central america',
    'laos': 'asia',
    'ecuador': 'south america',
    'taiwan': 'asia',
    'haiti': 'central america',
    'columbia': 'south america',
    'hungary': 'europe',
    'guatemala': 'central america',
    'nicaragua': 'central america',
    'scotland': 'europe',
    'thailand': 'asia',
    'yugoslavia': 'europe',
    'el-salvador': 'central america',
    'trinadad&tobago': 'central america',
    'peru': 'south america',
    'hong': 'asia',
    'other': 'other',
    'holand-netherlands': 'europe'
})

In [366]:
adult_df['native_region'].unique()

array(['north america', 'central america', 'asia', 'other',
       'south america', 'europe'], dtype=object)